# Generated by Django 6.0.6 on 2026-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('enqdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('jbseeker', 'Job Seerker'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=15)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
