# Generated by Django 6.0.6 on 2026-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_skill_jobseeker_experience_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='usertype',
            field=models.CharField(choices=[('jbseeker', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=15),
        ),
    ]
