# Generated by Django 6.0.6 on 2026-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_logininfo_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='usertype',
            field=models.CharField(choices=[('jbseeker', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=15),
        ),
    ]
